# Generated by Django 5.2.6 on 2025-12-30 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('company_code', models.CharField(blank=True, max_length=5, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Format: 2 letters, 2 digits, E or N', regex='^[A-Za-z]{2}[0-9]{2}[EN]$')])),
                ('strength', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('website', models.URLField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
